name: Build, Push to ECR & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: "043206426805"
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "april-class"
  EKS_CLUSTER: "app-eks-cluster"
  NAMESPACE: "config"
  RELEASE_NAME: "april-app"

concurrency:
  group: build-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          echo "Building ${IMAGE_URI}"
          docker build -t "${IMAGE_URI}" .

          echo "Pushing ${IMAGE_URI}"
          docker push "${IMAGE_URI}"
          echo "image_uri=${IMAGE_URI}" >> $GITHUB_ENV

  deploy:
    name: Deploy to EKS (Helm uninstall step)
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name "${{ env.EKS_CLUSTER }}" \
            --region "${{ env.AWS_REGION }}"

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Helm upgrade/install
        env:
           IMAGE_TAG: ${{ github.run_number }}
           CHART: ./web-app
        run: |
           ECR_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}"
           helm upgrade --install "${{ env.RELEASE_NAME }}" ${{ env.CHART }} \
             -n "${{ env.NAMESPACE }}" --create-namespace \
             --set image.repository="${ECR_URI}" \
             --set image.tag="${IMAGE_TAG}" \
             -f ${{ env.CHART }}/values.yaml
